words = {
 'abolir': {'il/elle': 'abolit',
            'ils/elles': 'abolissent',
            'je': 'abolis',
            'nous': 'abolissons',
            'tu': 'abolis',
            'vous': 'abolissez'},
 'accepter': {'il/elle': 'accepte',
              'ils/elles': 'acceptent',
              'je': 'accepte',
              'nous': 'acceptons',
              'tu': 'acceptes',
              'vous': 'acceptez'},
 'accomplir': {'il/elle': 'accomplit',
               'ils/elles': 'accomplissent',
               'je': 'accomplis',
               'nous': 'accomplissons',
               'tu': 'accomplis',
               'vous': 'accomplissez'},
 'accueillir': {'il/elle': 'accueille',
                'ils/elles': 'accueillent',
                'je': 'accueille',
                'nous': 'accueillons',
                'tu': 'accueilles',
                'vous': 'accueillez'},
 'adorer': {'il/elle': 'adore',
            'ils/elles': 'adorent',
            'je': 'adore',
            'nous': 'adorons',
            'tu': 'adores',
            'vous': 'adorez'},
 'affaiblir': {'il/elle': 'affaiblit',
               'ils/elles': 'affaiblissent',
               'je': 'affaiblis',
               'nous': 'affaiblissons',
               'tu': 'affaiblis',
               'vous': 'affaiblissez'},
 'agir': {'il/elle': 'agit',
          'ils/elles': 'agissent',
          'je': 'agis',
          'nous': 'agissons',
          'tu': 'agis',
          'vous': 'agissez'},
 'aimer': {'il/elle': 'aime',
           'ils/elles': 'aiment',
           'je': 'aime',
           'nous': 'aimons',
           'tu': 'aimes',
           'vous': 'aimez'},
 'annuler': {'il/elle': 'annule',
             'ils/elles': 'annulent',
             'je': 'annule',
             'nous': 'annulons',
             'tu': 'annules',
             'vous': 'annulez'},
 'apporter': {'il/elle': 'apporte',
              'ils/elles': 'apportent',
              'je': 'apporte',
              'nous': 'apportons',
              'tu': 'apportes',
              'vous': 'apportez'},
 'attendre': {'il/elle': 'attend',
              'ils/elles': 'attendent',
              'je': 'attends',
              'nous': 'attendons',
              'tu': 'attends',
              'vous': 'attendez'},
 'attraper': {'il/elle': 'attrape',
              'ils/elles': 'attrapent',
              'je': 'attrape',
              'nous': 'attrapons',
              'tu': 'attrapes',
              'vous': 'attrapez'},
 'avertir': {'il/elle': 'avertit',
             'ils/elles': 'avertissent',
             'je': 'avertis',
             'nous': 'avertissons',
             'tu': 'avertis',
             'vous': 'avertissez'},
 'bavarder': {'il/elle': 'bavarde',
              'ils/elles': 'bavardent',
              'je': 'bavarde',
              'nous': 'bavardons',
              'tu': 'bavardes',
              'vous': 'bavardez'},
 'bâtir': {'il/elle': 'bâtit',
           'ils/elles': 'bâtissent',
           'je': 'bâtis',
           'nous': 'bâtissons',
           'tu': 'bâtis',
           'vous': 'bâtissez'},
 'bénir': {'il/elle': 'bénit',
           'ils/elles': 'bénissent',
           'je': 'bénis',
           'nous': 'bénissons',
           'tu': 'bénis',
           'vous': 'bénissez'},
 'casser': {'il/elle': 'casse',
            'ils/elles': 'cassent',
            'je': 'casse',
            'nous': 'cassons',
            'tu': 'casses',
            'vous': 'cassez'},
 'chanter': {'il/elle': 'chante',
             'ils/elles': 'chantent',
             'je': 'chante',
             'nous': 'chantons',
             'tu': 'chantes',
             'vous': 'chantez'},
 'chercher': {'il/elle': 'cherche',
              'ils/elles': 'cherchent',
              'je': 'cherche',
              'nous': 'cherchons',
              'tu': 'cherches',
              'vous': 'cherchez'},
 'choisir': {'il/elle': 'choisit',
             'ils/elles': 'choisissent',
             'je': 'choisis',
             'nous': 'choisissons',
             'tu': 'choisis',
             'vous': 'choisissez'},
 'commander': {'il/elle': 'commande',
               'ils/elles': 'commandent',
               'je': 'commande',
               'nous': 'commandons',
               'tu': 'commandes',
               'vous': 'commandez'},
 'commencer': {'il/elle': 'commence',
               'ils/elles': 'commencent',
               'je': 'commence',
               'nous': 'commençons',
               'tu': 'commences',
               'vous': 'commencez'},
 'couper': {'il/elle': 'coupe',
            'ils/elles': 'coupent',
            'je': 'coupe',
            'nous': 'coupons',
            'tu': 'coupes',
            'vous': 'coupez'},
 'danser': {'il/elle': 'danse',
            'ils/elles': 'dansent',
            'je': 'danse',
            'nous': 'dansons',
            'tu': 'danses',
            'vous': 'dansez'},
 'demander': {'il/elle': 'demande',
              'ils/elles': 'demandent',
              'je': 'demande',
              'nous': 'demandons',
              'tu': 'demandes',
              'vous': 'demandez'},
 'descendre': {'il/elle': 'descend',
               'ils/elles': 'descendent',
               'je': 'descends',
               'nous': 'descendons',
               'tu': 'descends',
               'vous': 'descendez'},
 'dessiner': {'il/elle': 'dessine',
              'ils/elles': 'dessinent',
              'je': 'dessine',
              'nous': 'dessinons',
              'tu': 'dessines',
              'vous': 'dessinez'},
 'donner': {'il/elle': 'donne',
            'ils/elles': 'donnent',
            'je': 'donne',
            'nous': 'donnons',
            'tu': 'donnes',
            'vous': 'donnez'},
 'défendre': {'il/elle': 'défend',
              'ils/elles': 'défendent',
              'je': 'défends',
              'nous': 'défendons',
              'tu': 'défends',
              'vous': 'défendez'},
 'dépendre': {'il/elle': 'dépend',
              'ils/elles': 'dépendent',
              'je': 'dépends',
              'nous': 'dépendons',
              'tu': 'dépends',
              'vous': 'dépendez'},
 'détendre': {'il/elle': 'détend',
              'ils/elles': 'détendent',
              'je': 'détends',
              'nous': 'détendons',
              'tu': 'détends',
              'vous': 'détendez'},
 'détester': {'il/elle': 'déteste',
              'ils/elles': 'détestent',
              'je': 'déteste',
              'nous': 'détestons',
              'tu': 'détestes',
              'vous': 'détestez'},
 'embellir': {'il/elle': 'embellit',
              'ils/elles': 'embellissent',
              'je': 'embellis',
              'nous': 'embellissons',
              'tu': 'embellis',
              'vous': 'embellissez'},
 'emprunter': {'il/elle': 'emprunte',
               'ils/elles': 'empruntent',
               'je': 'emprunte',
               'nous': 'empruntons',
               'tu': 'empruntes',
               'vous': 'empruntez'},
 'enlever': {'il/elle': 'enlève',
             'ils/elles': 'enlèvent',
             'je': 'enlève',
             'nous': 'enlevons',
             'tu': 'enlèves',
             'vous': 'enlevez'},
 'entendre': {'il/elle': 'entend',
              'ils/elles': 'entendent',
              'je': 'entends',
              'nous': 'entendons',
              'tu': 'entends',
              'vous': 'entendez'},
 'envahir': {'il/elle': 'envahit',
             'ils/elles': 'envahissent',
             'je': 'envahis',
             'nous': 'envahissons',
             'tu': 'envahis',
             'vous': 'envahissez'},
 'exprimer': {'il/elle': 'exprime',
              'ils/elles': 'expriment',
              'je': 'exprime',
              'nous': 'exprimons',
              'tu': 'exprimes',
              'vous': 'exprimez'},
 'fendre': {'il/elle': 'fend',
            'ils/elles': 'fendent',
            'je': 'fends',
            'nous': 'fendons',
            'tu': 'fends',
            'vous': 'fendez'},
 'fermer': {'il/elle': 'ferme',
            'ils/elles': 'ferment',
            'je': 'ferme',
            'nous': 'fermons',
            'tu': 'fermes',
            'vous': 'fermez'},
 'finir': {'il/elle': 'finit',
           'ils/elles': 'finissent',
           'je': 'finis',
           'nous': 'finissons',
           'tu': 'finis',
           'vous': 'finissez'},
 'fondre': {'il/elle': 'fond',
            'ils/elles': 'fondent',
            'je': 'fonds',
            'nous': 'fondons',
            'tu': 'fonds',
            'vous': 'fondez'},
 'franchir': {'il/elle': 'franchit',
              'ils/elles': 'franchissent',
              'je': 'franchis',
              'nous': 'franchissons',
              'tu': 'franchis',
              'vous': 'franchissez'},
 'gagner': {'il/elle': 'gagne',
            'ils/elles': 'gagnent',
            'je': 'gagne',
            'nous': 'gagnons',
            'tu': 'gagnes',
            'vous': 'gagnez'},
 'garder': {'il/elle': 'garde',
            'ils/elles': 'gardent',
            'je': 'garde',
            'nous': 'gardons',
            'tu': 'gardes',
            'vous': 'gardez'},
 'goûter': {'il/elle': 'goûte',
            'ils/elles': 'goûtent',
            'je': 'goûte',
            'nous': 'goûtons',
            'tu': 'goûtes',
            'vous': 'goûtez'},
 'grandir': {'il/elle': 'grandit',
             'ils/elles': 'grandissent',
             'je': 'grandis',
             'nous': 'grandissons',
             'tu': 'grandis',
             'vous': 'grandissez'},
 'grossir': {'il/elle': 'grossit',
             'ils/elles': 'grossissent',
             'je': 'grossis',
             'nous': 'grossissons',
             'tu': 'grossis',
             'vous': 'grossissez'},
 'guérir': {'il/elle': 'guérit',
            'ils/elles': 'guérissent',
            'je': 'guéris',
            'nous': 'guérissons',
            'tu': 'guéris',
            'vous': 'guérissez'},
 'habiter': {'il/elle': 'habite',
             'ils/elles': 'habitent',
             'je': 'habite',
             'nous': 'habitons',
             'tu': 'habites',
             'vous': 'habitez'},
 'investir': {'il/elle': 'investit',
              'ils/elles': 'investissent',
              'je': 'investis',
              'nous': 'investissons',
              'tu': 'investis',
              'vous': 'investissez'},
 'jouer': {'il/elle': 'joue',
           'ils/elles': 'jouent',
           'je': 'joue',
           'nous': 'jouons',
           'tu': 'joues',
           'vous': 'jouez'},
 'laver': {'il/elle': 'lave',
           'ils/elles': 'lavent',
           'je': 'lave',
           'nous': 'lavons',
           'tu': 'laves',
           'vous': 'lavez'},
 'maigrir': {'il/elle': 'maigrit',
             'ils/elles': 'maigrissent',
             'je': 'maigris',
             'nous': 'maigrissons',
             'tu': 'maigris',
             'vous': 'maigrissez'},
 'montrer': {'il/elle': 'montre',
             'ils/elles': 'montrent',
             'je': 'montre',
             'nous': 'montrons',
             'tu': 'montres',
             'vous': 'montrez'},
 'mordre': {'il/elle': 'mord',
            'ils/elles': 'mordent',
            'je': 'mords',
            'nous': 'mordons',
            'tu': 'mords',
            'vous': 'mordez'},
 'nourrir': {'il/elle': 'nourrit',
             'ils/elles': 'nourrissent',
             'je': 'nourris',
             'nous': 'nourrissons',
             'tu': 'nourris',
             'vous': 'nourrissez'},
 'obéir': {'il/elle': 'obéit',
           'ils/elles': 'obéissent',
           'je': 'obéis',
           'nous': 'obéissons',
           'tu': 'obéis',
           'vous': 'obéissez'},
 'oublier': {'il/elle': 'oublie',
             'ils/elles': 'oublient',
             'je': 'oublie',
             'nous': 'oublions',
             'tu': 'oublies',
             'vous': 'oubliez'},
 'parler': {'il/elle': 'parle',
            'ils/elles': 'parlent',
            'je': 'parle',
            'nous': 'parlons',
            'tu': 'parles',
            'vous': 'parlez'},
 'pendre': {'il/elle': 'pend',
            'ils/elles': 'pendent',
            'je': 'pends',
            'nous': 'pendons',
            'tu': 'pends',
            'vous': 'pendez'},
 'penser': {'il/elle': 'pense',
            'ils/elles': 'pensent',
            'je': 'pense',
            'nous': 'pensons',
            'tu': 'penses',
            'vous': 'pensez'},
 'perdre': {'il/elle': 'perd',
            'ils/elles': 'perdent',
            'je': 'perds',
            'nous': 'perdons',
            'tu': 'perds',
            'vous': 'perdez'},
 'porter': {'il/elle': 'porte',
            'ils/elles': 'portent',
            'je': 'porte',
            'nous': 'portons',
            'tu': 'portes',
            'vous': 'portez'},
 'présenter': {'il/elle': 'présente',
               'ils/elles': 'présentent',
               'je': 'présente',
               'nous': 'présentons',
               'tu': 'présentes',
               'vous': 'présentez'},
 'prétendre': {'il/elle': 'prétend',
               'ils/elles': 'prétendent',
               'je': 'prétends',
               'nous': 'prétendons',
               'tu': 'prétends',
               'vous': 'prétendez'},
 'prêter': {'il/elle': 'prête',
            'ils/elles': 'prêtent',
            'je': 'prête',
            'nous': 'prêtons',
            'tu': 'prêtes',
            'vous': 'prêtez'},
 'punir': {'il/elle': 'punit',
           'ils/elles': 'punissent',
           'je': 'punis',
           'nous': 'punissons',
           'tu': 'punis',
           'vous': 'punissez'},
 'ralentir': {'il/elle': 'ralentit',
              'ils/elles': 'ralentissent',
              'je': 'ralentis',
              'nous': 'ralentissons',
              'tu': 'ralentis',
              'vous': 'ralentissez'},
 'refuser': {'il/elle': 'refuse',
             'ils/elles': 'refusent',
             'je': 'refuse',
             'nous': 'refusons',
             'tu': 'refuses',
             'vous': 'refusez'},
 'regarder': {'il/elle': 'regarde',
              'ils/elles': 'regardent',
              'je': 'regarde',
              'nous': 'regardons',
              'tu': 'regardes',
              'vous': 'regardez'},
 'remplir': {'il/elle': 'remplit',
             'ils/elles': 'remplissent',
             'je': 'remplis',
             'nous': 'remplissons',
             'tu': 'remplis',
             'vous': 'remplissez'},
 'rencontrer': {'il/elle': 'rencontre',
                'ils/elles': 'rencontrent',
                'je': 'rencontre',
                'nous': 'rencontrons',
                'tu': 'rencontres',
                'vous': 'rencontrez'},
 'rendre': {'il/elle': 'rend',
            'ils/elles': 'rendent',
            'je': 'rends',
            'nous': 'rendons',
            'tu': 'rends',
            'vous': 'rendez'},
 'rester': {'il/elle': 'reste',
            'ils/elles': 'restent',
            'je': 'reste',
            'nous': 'restons',
            'tu': 'restes',
            'vous': 'restez'},
 'rougir': {'il/elle': 'rougit',
            'ils/elles': 'rougissent',
            'je': 'rougis',
            'nous': 'rougissons',
            'tu': 'rougis',
            'vous': 'rougissez'},
 'réfléchir': {'il/elle': 'réfléchit',
               'ils/elles': 'réfléchissent',
               'je': 'réfléchis',
               'nous': 'réfléchissons',
               'tu': 'réfléchis',
               'vous': 'réfléchissez'},
 'répandre': {'il/elle': 'répand',
              'ils/elles': 'répandent',
              'je': 'répands',
              'nous': 'répandons',
              'tu': 'répands',
              'vous': 'répandez'},
 'répondre': {'il/elle': 'répond',
              'ils/elles': 'répondent',
              'je': 'réponds',
              'nous': 'répondons',
              'tu': 'réponds',
              'vous': 'répondez'},
 'réunir': {'il/elle': 'réunit',
            'ils/elles': 'réunissent',
            'je': 'réunis',
            'nous': 'réunissons',
            'tu': 'réunis',
            'vous': 'réunissez'},
 'réussir': {'il/elle': 'réussit',
             'ils/elles': 'réussissent',
             'je': 'réussis',
             'nous': 'réussissons',
             'tu': 'réussis',
             'vous': 'réussissez'},
 'rêver': {'il/elle': 'rêve',
           'ils/elles': 'rêvent',
           'je': 'rêve',
           'nous': 'rêvons',
           'tu': 'rêves',
           'vous': 'rêvez'},
 'saisir': {'il/elle': 'saisit',
            'ils/elles': 'saisissent',
            'je': 'saisis',
            'nous': 'saisissons',
            'tu': 'saisis',
            'vous': 'saisissez'},
 'saluer': {'il/elle': 'salue',
            'ils/elles': 'saluent',
            'je': 'salue',
            'nous': 'saluons',
            'tu': 'salues',
            'vous': 'saluez'},
 'sauter': {'il/elle': 'saute',
            'ils/elles': 'sautent',
            'je': 'saute',
            'nous': 'sautons',
            'tu': 'sautes',
            'vous': 'sautez'},
 'sembler': {'il/elle': 'semble',
             'ils/elles': 'semblent',
             'je': 'semble',
             'nous': 'semblons',
             'tu': 'sembles',
             'vous': 'semblez'},
 'skier': {'il/elle': 'skie',
           'ils/elles': 'skient',
           'je': 'skie',
           'nous': 'skions',
           'tu': 'skies',
           'vous': 'skiez'},
 'tendre': {'il/elle': 'tend',
            'ils/elles': 'tendent',
            'je': 'tends',
            'nous': 'tendons',
            'tu': 'tends',
            'vous': 'tendez'},
 'tomber': {'il/elle': 'tombe',
            'ils/elles': 'tombent',
            'je': 'tombe',
            'nous': 'tombons',
            'tu': 'tombes',
            'vous': 'tombez'},
 'travailler': {'il/elle': 'travaille',
                'ils/elles': 'travaillent',
                'je': 'travaille',
                'nous': 'travaillons',
                'tu': 'travailles',
                'vous': 'travaillez'},
 'trouver': {'il/elle': 'trouve',
             'ils/elles': 'trouvent',
             'je': 'trouve',
             'nous': 'trouvons',
             'tu': 'trouves',
             'vous': 'trouvez'},
 'téléphoner': {'il/elle': 'téléphone',
                'ils/elles': 'téléphonent',
                'je': 'téléphone',
                'nous': 'téléphonons',
                'tu': 'téléphones',
                'vous': 'téléphonez'},
 'utiliser': {'il/elle': 'utilise',
              'ils/elles': 'utilisent',
              'je': 'utilise',
              'nous': 'utilisons',
              'tu': 'utilises',
              'vous': 'utilisez'},
 'vendre': {'il/elle': 'vend',
            'ils/elles': 'vendent',
            'je': 'vends',
            'nous': 'vendons',
            'tu': 'vends',
            'vous': 'vendez'},
 'vieillir': {'il/elle': 'vieillit',
              'ils/elles': 'vieillissent',
              'je': 'vieillis',
              'nous': 'vieillissons',
              'tu': 'vieillis',
              'vous': 'vieillissez'},
 'visiter': {'il/elle': 'visite',
             'ils/elles': 'visitent',
             'je': 'visite',
             'nous': 'visitons',
             'tu': 'visites',
             'vous': 'visitez'},
 'voler': {'il/elle': 'vole',
           'ils/elles': 'volent',
           'je': 'vole',
           'nous': 'volons',
           'tu': 'voles',
           'vous': 'volez'},
 'écouter': {'il/elle': 'écoute',
             'ils/elles': 'écoutent',
             'je': 'écoute',
             'nous': 'écoutons',
             'tu': 'écoutes',
             'vous': 'écoutez'},
 'établir': {'il/elle': 'établit',
             'ils/elles': 'établissent',
             'je': 'établis',
             'nous': 'établissons',
             'tu': 'établis',
             'vous': 'établissez'},
 'étendre': {'il/elle': 'étend',
             'ils/elles': 'étendent',
             'je': 'étends',
             'nous': 'étendons',
             'tu': 'étends',
             'vous': 'étendez'},
 'étourdir': {'il/elle': 'étourdit',
              'ils/elles': 'étourdissent',
              'je': 'étourdis',
              'nous': 'étourdissons',
              'tu': 'étourdis',
              'vous': 'étourdissez'},
 'étudier': {'il/elle': 'étudie',
             'ils/elles': 'étudient',
             'je': 'étudie',
             'nous': 'étudions',
             'tu': 'étudies',
             'vous': 'étudiez'}}
