words = {
 'abolir': {'je': 'abolis',
            'tu': 'abolis',
            'il/elle': 'abolit',
            'nous': 'abolissons',
            'vous': 'abolissez',
            'ils/elles': 'abolissent'},
 'accepter': {'je': 'accepte',
              'tu': 'acceptes',
              'il/elle': 'accepte',
              'nous': 'acceptons',
              'vous': 'acceptez',
              'ils/elles': 'acceptent'},
 'accomplir': {'je': 'accomplis',
               'tu': 'accomplis',
               'il/elle': 'accomplit',
               'nous': 'accomplissons',
               'vous': 'accomplissez',
               'ils/elles': 'accomplissent'},
 'accueillir': {'je': 'accueille',
                'tu': 'accueilles',
                'il/elle': 'accueille',
                'nous': 'accueillons',
                'vous': 'accueillez',
                'ils/elles': 'accueillent'},
 'adorer': {'je': 'adore',
            'tu': 'adores',
            'il/elle': 'adore',
            'nous': 'adorons',
            'vous': 'adorez',
            'ils/elles': 'adorent'},
 'affaiblir': {'je': 'affaiblis',
               'tu': 'affaiblis',
               'il/elle': 'affaiblit',
               'nous': 'affaiblissons',
               'vous': 'affaiblissez',
               'ils/elles': 'affaiblissent'},
 'agir': {'je': 'agis',
          'tu': 'agis',
          'il/elle': 'agit',
          'nous': 'agissons',
          'vous': 'agissez',
          'ils/elles': 'agissent'},
 'aimer': {'je': 'aime',
           'tu': 'aimes',
           'il/elle': 'aime',
           'nous': 'aimons',
           'vous': 'aimez',
           'ils/elles': 'aiment'},
 'annuler': {'je': 'annule',
             'tu': 'annules',
             'il/elle': 'annule',
             'nous': 'annulons',
             'vous': 'annulez',
             'ils/elles': 'annulent'},
 'apporter': {'je': 'apporte',
              'tu': 'apportes',
              'il/elle': 'apporte',
              'nous': 'apportons',
              'vous': 'apportez',
              'ils/elles': 'apportent'},
 'attendre': {'je': 'attends',
              'tu': 'attends',
              'il/elle': 'attend',
              'nous': 'attendons',
              'vous': 'attendez',
              'ils/elles': 'attendent'},
 'attraper': {'je': 'attrape',
              'tu': 'attrapes',
              'il/elle': 'attrape',
              'nous': 'attrapons',
              'vous': 'attrapez',
              'ils/elles': 'attrapent'},
 'avertir': {'je': 'avertis',
             'tu': 'avertis',
             'il/elle': 'avertit',
             'nous': 'avertissons',
             'vous': 'avertissez',
             'ils/elles': 'avertissent'},
 'bavarder': {'je': 'bavarde',
              'tu': 'bavardes',
              'il/elle': 'bavarde',
              'nous': 'bavardons',
              'vous': 'bavardez',
              'ils/elles': 'bavardent'},
 'bâtir': {'je': 'bâtis',
           'tu': 'bâtis',
           'il/elle': 'bâtit',
           'nous': 'bâtissons',
           'vous': 'bâtissez',
           'ils/elles': 'bâtissent'},
 'bénir': {'je': 'bénis',
           'tu': 'bénis',
           'il/elle': 'bénit',
           'nous': 'bénissons',
           'vous': 'bénissez',
           'ils/elles': 'bénissent'},
 'casser': {'je': 'casse',
            'tu': 'casses',
            'il/elle': 'casse',
            'nous': 'cassons',
            'vous': 'cassez',
            'ils/elles': 'cassent'},
 'chanter': {'je': 'chante',
             'tu': 'chantes',
             'il/elle': 'chante',
             'nous': 'chantons',
             'vous': 'chantez',
             'ils/elles': 'chantent'},
 'chercher': {'je': 'cherche',
              'tu': 'cherches',
              'il/elle': 'cherche',
              'nous': 'cherchons',
              'vous': 'cherchez',
              'ils/elles': 'cherchent'},
 'choisir': {'je': 'choisis',
             'tu': 'choisis',
             'il/elle': 'choisit',
             'nous': 'choisissons',
             'vous': 'choisissez',
             'ils/elles': 'choisissent'},
 'commander': {'je': 'commande',
               'tu': 'commandes',
               'il/elle': 'commande',
               'nous': 'commandons',
               'vous': 'commandez',
               'ils/elles': 'commandent'},
 'commencer': {'je': 'commence',
               'tu': 'commences',
               'il/elle': 'commence',
               'nous': 'commençons',
               'vous': 'commencez',
               'ils/elles': 'commencent'},
 'couper': {'je': 'coupe',
            'tu': 'coupes',
            'il/elle': 'coupe',
            'nous': 'coupons',
            'vous': 'coupez',
            'ils/elles': 'coupent'},
 'danser': {'je': 'danse',
            'tu': 'danses',
            'il/elle': 'danse',
            'nous': 'dansons',
            'vous': 'dansez',
            'ils/elles': 'dansent'},
 'demander': {'je': 'demande',
              'tu': 'demandes',
              'il/elle': 'demande',
              'nous': 'demandons',
              'vous': 'demandez',
              'ils/elles': 'demandent'},
 'descendre': {'je': 'descends',
               'tu': 'descends',
               'il/elle': 'descend',
               'nous': 'descendons',
               'vous': 'descendez',
               'ils/elles': 'descendent'},
 'dessiner': {'je': 'dessine',
              'tu': 'dessines',
              'il/elle': 'dessine',
              'nous': 'dessinons',
              'vous': 'dessinez',
              'ils/elles': 'dessinent'},
 'donner': {'je': 'donne',
            'tu': 'donnes',
            'il/elle': 'donne',
            'nous': 'donnons',
            'vous': 'donnez',
            'ils/elles': 'donnent'},
 'défendre': {'je': 'défends',
              'tu': 'défends',
              'il/elle': 'défend',
              'nous': 'défendons',
              'vous': 'défendez',
              'ils/elles': 'défendent'},
 'dépendre': {'je': 'dépends',
              'tu': 'dépends',
              'il/elle': 'dépend',
              'nous': 'dépendons',
              'vous': 'dépendez',
              'ils/elles': 'dépendent'},
 'détendre': {'je': 'détends',
              'tu': 'détends',
              'il/elle': 'détend',
              'nous': 'détendons',
              'vous': 'détendez',
              'ils/elles': 'détendent'},
 'détester': {'je': 'déteste',
              'tu': 'détestes',
              'il/elle': 'déteste',
              'nous': 'détestons',
              'vous': 'détestez',
              'ils/elles': 'détestent'},
 'embellir': {'je': 'embellis',
              'tu': 'embellis',
              'il/elle': 'embellit',
              'nous': 'embellissons',
              'vous': 'embellissez',
              'ils/elles': 'embellissent'},
 'emprunter': {'je': 'emprunte',
               'tu': 'empruntes',
               'il/elle': 'emprunte',
               'nous': 'empruntons',
               'vous': 'empruntez',
               'ils/elles': 'empruntent'},
 'enlever': {'je': 'enlève',
             'tu': 'enlèves',
             'il/elle': 'enlève',
             'nous': 'enlevons',
             'vous': 'enlevez',
             'ils/elles': 'enlèvent'},
 'entendre': {'je': 'entends',
              'tu': 'entends',
              'il/elle': 'entend',
              'nous': 'entendons',
              'vous': 'entendez',
              'ils/elles': 'entendent'},
 'envahir': {'je': 'envahis',
             'tu': 'envahis',
             'il/elle': 'envahit',
             'nous': 'envahissons',
             'vous': 'envahissez',
             'ils/elles': 'envahissent'},
 'exprimer': {'je': 'exprime',
              'tu': 'exprimes',
              'il/elle': 'exprime',
              'nous': 'exprimons',
              'vous': 'exprimez',
              'ils/elles': 'expriment'},
 'fendre': {'je': 'fends',
            'tu': 'fends',
            'il/elle': 'fend',
            'nous': 'fendons',
            'vous': 'fendez',
            'ils/elles': 'fendent'},
 'fermer': {'je': 'ferme',
            'tu': 'fermes',
            'il/elle': 'ferme',
            'nous': 'fermons',
            'vous': 'fermez',
            'ils/elles': 'ferment'},
 'finir': {'je': 'finis',
           'tu': 'finis',
           'il/elle': 'finit',
           'nous': 'finissons',
           'vous': 'finissez',
           'ils/elles': 'finissent'},
 'fondre': {'je': 'fonds',
            'tu': 'fonds',
            'il/elle': 'fond',
            'nous': 'fondons',
            'vous': 'fondez',
            'ils/elles': 'fondent'},
 'franchir': {'je': 'franchis',
              'tu': 'franchis',
              'il/elle': 'franchit',
              'nous': 'franchissons',
              'vous': 'franchissez',
              'ils/elles': 'franchissent'},
 'gagner': {'je': 'gagne',
            'tu': 'gagnes',
            'il/elle': 'gagne',
            'nous': 'gagnons',
            'vous': 'gagnez',
            'ils/elles': 'gagnent'},
 'garder': {'je': 'garde',
            'tu': 'gardes',
            'il/elle': 'garde',
            'nous': 'gardons',
            'vous': 'gardez',
            'ils/elles': 'gardent'},
 'goûter': {'je': 'goûte',
            'tu': 'goûtes',
            'il/elle': 'goûte',
            'nous': 'goûtons',
            'vous': 'goûtez',
            'ils/elles': 'goûtent'},
 'grandir': {'je': 'grandis',
             'tu': 'grandis',
             'il/elle': 'grandit',
             'nous': 'grandissons',
             'vous': 'grandissez',
             'ils/elles': 'grandissent'},
 'grossir': {'je': 'grossis',
             'tu': 'grossis',
             'il/elle': 'grossit',
             'nous': 'grossissons',
             'vous': 'grossissez',
             'ils/elles': 'grossissent'},
 'guérir': {'je': 'guéris',
            'tu': 'guéris',
            'il/elle': 'guérit',
            'nous': 'guérissons',
            'vous': 'guérissez',
            'ils/elles': 'guérissent'},
 'habiter': {'je': 'habite',
             'tu': 'habites',
             'il/elle': 'habite',
             'nous': 'habitons',
             'vous': 'habitez',
             'ils/elles': 'habitent'},
 'investir': {'je': 'investis',
              'tu': 'investis',
              'il/elle': 'investit',
              'nous': 'investissons',
              'vous': 'investissez',
              'ils/elles': 'investissent'},
 'jouer': {'je': 'joue',
           'tu': 'joues',
           'il/elle': 'joue',
           'nous': 'jouons',
           'vous': 'jouez',
           'ils/elles': 'jouent'},
 'laver': {'je': 'lave',
           'tu': 'laves',
           'il/elle': 'lave',
           'nous': 'lavons',
           'vous': 'lavez',
           'ils/elles': 'lavent'},
 'maigrir': {'je': 'maigris',
             'tu': 'maigris',
             'il/elle': 'maigrit',
             'nous': 'maigrissons',
             'vous': 'maigrissez',
             'ils/elles': 'maigrissent'},
 'montrer': {'je': 'montre',
             'tu': 'montres',
             'il/elle': 'montre',
             'nous': 'montrons',
             'vous': 'montrez',
             'ils/elles': 'montrent'},
 'mordre': {'je': 'mords',
            'tu': 'mords',
            'il/elle': 'mord',
            'nous': 'mordons',
            'vous': 'mordez',
            'ils/elles': 'mordent'},
 'nourrir': {'je': 'nourris',
             'tu': 'nourris',
             'il/elle': 'nourrit',
             'nous': 'nourrissons',
             'vous': 'nourrissez',
             'ils/elles': 'nourrissent'},
 'obéir': {'je': 'obéis',
           'tu': 'obéis',
           'il/elle': 'obéit',
           'nous': 'obéissons',
           'vous': 'obéissez',
           'ils/elles': 'obéissent'},
 'oublier': {'je': 'oublie',
             'tu': 'oublies',
             'il/elle': 'oublie',
             'nous': 'oublions',
             'vous': 'oubliez',
             'ils/elles': 'oublient'},
 'parler': {'je': 'parle',
            'tu': 'parles',
            'il/elle': 'parle',
            'nous': 'parlons',
            'vous': 'parlez',
            'ils/elles': 'parlent'},
 'pendre': {'je': 'pends',
            'tu': 'pends',
            'il/elle': 'pend',
            'nous': 'pendons',
            'vous': 'pendez',
            'ils/elles': 'pendent'},
 'penser': {'je': 'pense',
            'tu': 'penses',
            'il/elle': 'pense',
            'nous': 'pensons',
            'vous': 'pensez',
            'ils/elles': 'pensent'},
 'perdre': {'je': 'perds',
            'tu': 'perds',
            'il/elle': 'perd',
            'nous': 'perdons',
            'vous': 'perdez',
            'ils/elles': 'perdent'},
 'porter': {'je': 'porte',
            'tu': 'portes',
            'il/elle': 'porte',
            'nous': 'portons',
            'vous': 'portez',
            'ils/elles': 'portent'},
 'présenter': {'je': 'présente',
               'tu': 'présentes',
               'il/elle': 'présente',
               'nous': 'présentons',
               'vous': 'présentez',
               'ils/elles': 'présentent'},
 'prétendre': {'je': 'prétends',
               'tu': 'prétends',
               'il/elle': 'prétend',
               'nous': 'prétendons',
               'vous': 'prétendez',
               'ils/elles': 'prétendent'},
 'prêter': {'je': 'prête',
            'tu': 'prêtes',
            'il/elle': 'prête',
            'nous': 'prêtons',
            'vous': 'prêtez',
            'ils/elles': 'prêtent'},
 'punir': {'je': 'punis',
           'tu': 'punis',
           'il/elle': 'punit',
           'nous': 'punissons',
           'vous': 'punissez',
           'ils/elles': 'punissent'},
 'ralentir': {'je': 'ralentis',
              'tu': 'ralentis',
              'il/elle': 'ralentit',
              'nous': 'ralentissons',
              'vous': 'ralentissez',
              'ils/elles': 'ralentissent'},
 'refuser': {'je': 'refuse',
             'tu': 'refuses',
             'il/elle': 'refuse',
             'nous': 'refusons',
             'vous': 'refusez',
             'ils/elles': 'refusent'},
 'regarder': {'je': 'regarde',
              'tu': 'regardes',
              'il/elle': 'regarde',
              'nous': 'regardons',
              'vous': 'regardez',
              'ils/elles': 'regardent'},
 'remplir': {'je': 'remplis',
             'tu': 'remplis',
             'il/elle': 'remplit',
             'nous': 'remplissons',
             'vous': 'remplissez',
             'ils/elles': 'remplissent'},
 'rencontrer': {'je': 'rencontre',
                'tu': 'rencontres',
                'il/elle': 'rencontre',
                'nous': 'rencontrons',
                'vous': 'rencontrez',
                'ils/elles': 'rencontrent'},
 'rendre': {'je': 'rends',
            'tu': 'rends',
            'il/elle': 'rend',
            'nous': 'rendons',
            'vous': 'rendez',
            'ils/elles': 'rendent'},
 'rester': {'je': 'reste',
            'tu': 'restes',
            'il/elle': 'reste',
            'nous': 'restons',
            'vous': 'restez',
            'ils/elles': 'restent'},
 'rougir': {'je': 'rougis',
            'tu': 'rougis',
            'il/elle': 'rougit',
            'nous': 'rougissons',
            'vous': 'rougissez',
            'ils/elles': 'rougissent'},
 'réfléchir': {'je': 'réfléchis',
               'tu': 'réfléchis',
               'il/elle': 'réfléchit',
               'nous': 'réfléchissons',
               'vous': 'réfléchissez',
               'ils/elles': 'réfléchissent'},
 'répandre': {'je': 'répands',
              'tu': 'répands',
              'il/elle': 'répand',
              'nous': 'répandons',
              'vous': 'répandez',
              'ils/elles': 'répandent'},
 'répondre': {'je': 'réponds',
              'tu': 'réponds',
              'il/elle': 'répond',
              'nous': 'répondons',
              'vous': 'répondez',
              'ils/elles': 'répondent'},
 'réunir': {'je': 'réunis',
            'tu': 'réunis',
            'il/elle': 'réunit',
            'nous': 'réunissons',
            'vous': 'réunissez',
            'ils/elles': 'réunissent'},
 'réussir': {'je': 'réussis',
             'tu': 'réussis',
             'il/elle': 'réussit',
             'nous': 'réussissons',
             'vous': 'réussissez',
             'ils/elles': 'réussissent'},
 'rêver': {'je': 'rêve',
           'tu': 'rêves',
           'il/elle': 'rêve',
           'nous': 'rêvons',
           'vous': 'rêvez',
           'ils/elles': 'rêvent'},
 'saisir': {'je': 'saisis',
            'tu': 'saisis',
            'il/elle': 'saisit',
            'nous': 'saisissons',
            'vous': 'saisissez',
            'ils/elles': 'saisissent'},
 'saluer': {'je': 'salue',
            'tu': 'salues',
            'il/elle': 'salue',
            'nous': 'saluons',
            'vous': 'saluez',
            'ils/elles': 'saluent'},
 'sauter': {'je': 'saute',
            'tu': 'sautes',
            'il/elle': 'saute',
            'nous': 'sautons',
            'vous': 'sautez',
            'ils/elles': 'sautent'},
 'sembler': {'je': 'semble',
             'tu': 'sembles',
             'il/elle': 'semble',
             'nous': 'semblons',
             'vous': 'semblez',
             'ils/elles': 'semblent'},
 'skier': {'je': 'skie',
           'tu': 'skies',
           'il/elle': 'skie',
           'nous': 'skions',
           'vous': 'skiez',
           'ils/elles': 'skient'},
 'tendre': {'je': 'tends',
            'tu': 'tends',
            'il/elle': 'tend',
            'nous': 'tendons',
            'vous': 'tendez',
            'ils/elles': 'tendent'},
 'tomber': {'je': 'tombe',
            'tu': 'tombes',
            'il/elle': 'tombe',
            'nous': 'tombons',
            'vous': 'tombez',
            'ils/elles': 'tombent'},
 'travailler': {'je': 'travaille',
                'tu': 'travailles',
                'il/elle': 'travaille',
                'nous': 'travaillons',
                'vous': 'travaillez',
                'ils/elles': 'travaillent'},
 'trouver': {'je': 'trouve',
             'tu': 'trouves',
             'il/elle': 'trouve',
             'nous': 'trouvons',
             'vous': 'trouvez',
             'ils/elles': 'trouvent'},
 'téléphoner': {'je': 'téléphone',
                'tu': 'téléphones',
                'il/elle': 'téléphone',
                'nous': 'téléphonons',
                'vous': 'téléphonez',
                'ils/elles': 'téléphonent'},
 'utiliser': {'je': 'utilise',
              'tu': 'utilises',
              'il/elle': 'utilise',
              'nous': 'utilisons',
              'vous': 'utilisez',
              'ils/elles': 'utilisent'},
 'vendre': {'je': 'vends',
            'tu': 'vends',
            'il/elle': 'vend',
            'nous': 'vendons',
            'vous': 'vendez',
            'ils/elles': 'vendent'},
 'vieillir': {'je': 'vieillis',
              'tu': 'vieillis',
              'il/elle': 'vieillit',
              'nous': 'vieillissons',
              'vous': 'vieillissez',
              'ils/elles': 'vieillissent'},
 'visiter': {'je': 'visite',
             'tu': 'visites',
             'il/elle': 'visite',
             'nous': 'visitons',
             'vous': 'visitez',
             'ils/elles': 'visitent'},
 'voler': {'je': 'vole',
           'tu': 'voles',
           'il/elle': 'vole',
           'nous': 'volons',
           'vous': 'volez',
           'ils/elles': 'volent'},
 'écouter': {'je': 'écoute',
             'tu': 'écoutes',
             'il/elle': 'écoute',
             'nous': 'écoutons',
             'vous': 'écoutez',
             'ils/elles': 'écoutent'},
 'établir': {'je': 'établis',
             'tu': 'établis',
             'il/elle': 'établit',
             'nous': 'établissons',
             'vous': 'établissez',
             'ils/elles': 'établissent'},
 'étendre': {'je': 'étends',
             'tu': 'étends',
             'il/elle': 'étend',
             'nous': 'étendons',
             'vous': 'étendez',
             'ils/elles': 'étendent'},
 'étourdir': {'je': 'étourdis',
              'tu': 'étourdis',
              'il/elle': 'étourdit',
              'nous': 'étourdissons',
              'vous': 'étourdissez',
              'ils/elles': 'étourdissent'},
 'étudier': {'je': 'étudie',
             'tu': 'étudies',
             'il/elle': 'étudie',
             'nous': 'étudions',
             'vous': 'étudiez',
             'ils/elles': 'étudient'},
}
